server:
    port: 8080

spring:
    profiles:
        active: prod
    datasource:
        dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        url: jdbc:mysql://localhost:3306/springbootbase_prod?useUnicode=true&characterEncoding=utf8
        databaseName:
        serverName: 
        username: root
        password: 
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

    jpa:
        database-platform: org.hibernate.dialect.MySQLInnoDBDialect
        database: MYSQL
        openInView: false
        show_sql: false
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy

http:
    cache:
        timeToLiveInDays: 31

cache:
    timeToLiveSeconds: 3600
    ehcache:
        maxBytesLocalHeap: 256M
